spring:
  application:
    name: citas

  datasource:
    url: jdbc:postgresql://localhost:5432/medisalud_citas
    username: postgres
    password: warriors230
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: America/Bogota
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8083
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.medisalud.citas: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
