spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  error:
    include-message: never
    include-binding-errors: never
    include-exception: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    loggers:
      enabled: true

logging:
  level:
    root: INFO
    com.medisalud.citas: INFO
    org.hibernate: ERROR
