spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  error:
    include-message: never
    include-binding-errors: never
    include-exception: false

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    com.medisalud.citas: INFO
    org.hibernate: ERROR
